"""update foreign key for seller

Revision ID: 2ef2fa9cf318
Revises: 6ef8f10d124b
Create Date: 2026-07-29 10:43:50.103796

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ef2fa9cf318'
down_revision: Union[str, Sequence[str], None] = '6ef8f10d124b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments_table')
    op.drop_table('seller_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_table',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('seller_table_pkey'))
    )
    op.create_table('shipments_table',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PLACED', 'IN_TRANSIT', 'DELIVERED', 'PENDING', name='shipmentstatus'), autoincrement=False, nullable=False),
    sa.Column('estimated_delivery', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_table.id'], name=op.f('shipments_table_seller_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shipments_table_pkey'))
    )
    # ### end Alembic commands ###
