"""add shipment event table

Revision ID: 3a352310db5d
Revises: d30bc8c11203
Create Date: 2026-08-02 11:16:50.016904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a352310db5d'
down_revision: Union[str, Sequence[str], None] = 'd30bc8c11203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('status', postgresql.ENUM(name="shipmentstatus", create_type=False), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shipments_table', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shipments_table', sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments_table', 'zip_code')
    op.drop_column('shipments_table', 'address')
    op.drop_table('shipment_event')
    # ### end Alembic commands ###
