"""init

Revision ID: d30bc8c11203
Revises: 
Create Date: 2026-07-30 15:41:17.032708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd30bc8c11203'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # create enum only if it doesn't exist — DO blocks don't work with asyncpg
    existing_enums = [e['name'] for e in inspector.get_enums()]
    if 'shipmentstatus' not in existing_enums:
        sa.Enum('PLACED', 'IN_TRANSIT', 'DELIVERED', 'PENDING', name='shipmentstatus').create(conn)

    if not inspector.has_table('delivery_partner'):
        op.create_table('delivery_partner',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
        sa.Column('servicable_zipcodes', sa.ARRAY(sa.INTEGER()), nullable=True),
        sa.Column('max_handling_capacity', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    if not inspector.has_table('seller_table'):
        op.create_table('seller_table',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if not inspector.has_table('shipments_table'):
        op.create_table('shipments_table',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('weight', sa.Float(), nullable=False),
        sa.Column('status', postgresql.ENUM('PLACED', 'IN_TRANSIT', 'DELIVERED', 'PENDING', name='shipmentstatus', create_type=False), nullable=False),
        sa.Column('destination', sa.Integer(), nullable=False),
        sa.Column('estimated_delivery', sa.DateTime(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
        sa.Column('seller_id', sa.Uuid(), nullable=False),
        sa.Column('delivery_partner_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['delivery_partner_id'], ['delivery_partner.id'], ),
        sa.ForeignKeyConstraint(['seller_id'], ['seller_table.id'], ),
        sa.PrimaryKeyConstraint('id')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments_table')
    op.drop_table('seller_table')
    op.drop_table('delivery_partner')
    # ### end Alembic commands ###
